name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          backend/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Audit dependencies
      run: |
        cd backend
        npm audit

    - name: Type check
      run: |
        cd backend
        npm run type-check

    - name: Run linter
      run: |
        cd backend
        npm run lint

    - name: Run unit tests
      run: |
        cd backend
        npm test

    - name: Run e2e tests
      run: |
        cd backend
        npm run test:e2e

    - name: Run migration tests
      run: |
        cd backend
        npm run test:migrations

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        directory: ./backend/coverage
        flags: unittests,e2e,migrations
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true

  load-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: backend/dist

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install k6
      run: |
        curl -L https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz -o k6.tar.gz
        tar xzf k6.tar.gz
        sudo cp k6-v0.47.0-linux-amd64/k6 /usr/local/bin

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Start server
      run: |
        cd backend
        npm start &
        sleep 10

    - name: Run load tests
      run: |
        cd backend
        npm run test:load:ci

    - name: Upload load test results
      uses: actions/upload-artifact@v3
      with:
        name: load-test-results
        path: backend/load-test-results.json

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          backend/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-20-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-20-
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Build
      run: |
        cd backend
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: backend/dist 